### PR TITLE
Gfk 8 view list of all participants

### PR DESCRIPTION
**Pull request by anupam-maity**

### CODE REVIEW

**Comment by anupam-maity** [comment]
GFK-8

**Review by jayaraman-natesan — COMMENTED** [review]
Code review skipped for this test phase

**Review by jayaraman-natesan — COMMENTED** [review]
Review skipped for this mock

**Review by jayaraman-natesan — COMMENTED** [review]
REviewed

**Review by jayaraman-natesan — APPROVED** [review]
Review approved for mock

**Pull request merged**
